### ISSUE TITLE
Crash reporting missing Stack trace

### ISSUE THREAD

**Issue by robertoandrade** [vladikoff/chromeos-apk#148]
When one of my apps crashes with say a NullPointerException, the custom runtime doesn't seem like it's reporting the stack trace as the original does. On my DevTools console I see:

```
Received a crash
main.js:389 prod: ARC
main.js:389 arc_app_name: com.billguard.android
main.js:389 ptime: 3031
main.js:389 crash_time: Mon Jan 19 2015 13:33:20 GMT-0500 (EST)
main.js:389 ver: 38.4410.120.43
main.js:389 arc_build_tag: arc-runtime-38.4410.120.43
main.js:389 message: Android unhandled exception
main.js:389 chrome_version: 42.0.2281.0
main.js:389 app_id: jhimhgalpijaklfjaoagejejbbpaepfi
main.js:389 app_version: 1337
main.js:389 app_package_name: com.billguard.android
main.js:389 runtime_name: ARChon Custom Runtime 1.2 - x86_64
main.js:389 runtime_update_url: http://localhost
main.js:389 width: 960
main.js:389 height: 632
main.js:389 is_minimized: false
main.js:389 is_maximized: false
main.js:389 is_fullscreen: false
main.js:389 runtime_updated_while_running: null
main.js:389 log_message: java.lang.NullPointerException
main.js:389 arch: x86-64
main.js:389 nacl_arch: x86-64
main.js:389 os: mac
main.js:389
```

Below `log_message`, on the regular runtime there's also a node called `stack_trace` with the full exception trace so we can identify what's going on with the app. I traced this back to the call to `CrashReporter.prototype.reportCrash` (3rd parameter), which seems to be included in the local hash table that is composed to report the error. My guess is that when the runtime calls for this function, the value in the parameter is already omitted.

**Comment by robertoandrade** [comment]
After enabling ADB on my wrapped APK, I was able to fetch the stack trace and it looks like the NPE is caused by the runtime and not the app. In case this is something that can be fixed within the custom runtime I'm happy to open it as a separate issue if you believe it's necessary, let me know:

```
01-05 04:11:45.336 E/AndroidRuntime(  204): FATAL EXCEPTION: main
01-05 04:11:45.336 E/AndroidRuntime(  204): Process: com.billguard.android, PID: 204
01-05 04:11:45.336 E/AndroidRuntime(  204): java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
01-05 04:11:45.336 E/AndroidRuntime(  204): 	at android.os.Process$1.run(Process.java:424)
01-05 04:11:45.336 E/AndroidRuntime(  204): Caused by: java.lang.reflect.InvocationTargetException
01-05 04:11:45.336 E/AndroidRuntime(  204): 	at java.lang.reflect.Method.invokeNative(Native Method)
01-05 04:11:45.336 E/AndroidRuntime(  204): 	at java.lang.reflect.Method.invoke(Method.java:515)
01-05 04:11:45.336 E/AndroidRuntime(  204): 	at android.os.Process$1.run(Process.java:417)
01-05 04:11:45.336 E/AndroidRuntime(  204): Caused by: java.lang.NullPointerException
01-05 04:11:45.336 E/AndroidRuntime(  204): 	at android.view.HardwareRenderer$GlRenderer.createPbufferSurface(HardwareRenderer.java:1369)
01-05 04:11:45.336 E/AndroidRuntime(  204): 	at android.view.HardwareRenderer$Gl20Renderer.safelyRun(HardwareRenderer.java:2281)
01-05 04:11:45.336 E/AndroidRuntime(  204): 	at android.view.HardwareRenderer$Gl20Renderer.destroyHardwareResources(HardwareRenderer.java:2331)
01-05 04:11:45.336 E/AndroidRuntime(  204): 	at android.view.ViewRootImpl.destroyHardwareResources(ViewRootImpl.java:623)
01-05 04:11:45.336 E/AndroidRuntime(  204): 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1229)
01-05 04:11:45.336 E/AndroidRuntime(  204): 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:990)
01-05 04:11:45.336 E/AndroidRuntime(  204): 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5574)
01-05 04:11:45.336 E/AndroidRuntime(  204): 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:749)
01-05 04:11:45.336 E/AndroidRuntime(  204): 	at android.view.Choreographer.doCallbacks(Choreographer.java:562)
01-05 04:11:45.336 E/AndroidRuntime(  204): 	at android.view.Choreographer.doFrame(Choreographer.java:532)
01-05 04:11:45.336 E/AndroidRuntime(  204): 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:735)
01-05 04:11:45.336 E/AndroidRuntime(  204): 	at android.os.Handler.handleCallback(Handler.java:733)
01-05 04:11:45.336 E/AndroidRuntime(  204): 	at android.os.Handler.dispatchMessage(Handler.java:95)
01-05 04:11:45.336 E/AndroidRuntime(  204): 	at android.os.Looper.loop(Looper.java:156)
01-05 04:11:45.336 E/AndroidRuntime(  204): 	at android.app.ActivityThread.main(ActivityThread.java:5078)
01-05 04:11:45.336 E/AndroidRuntime(  204): 	... 3 more
```
