### ISSUE TITLE
java.io.FileNotFoundException: /data/data/com.tencent.mobileqq

### ISSUE THREAD

**Issue by sevk** [vladikoff/chromeos-apk#172]
java.io.FileNotFoundException: /data/data/com.tencent.mobileqq/files/Properties: open failed: ENOENT (No such file or directory)
	at libcore.io.IoBridge.open(IoBridge.java:409)
	at java.io.FileInputStream.<init>(FileInputStream.java:78)
	at android.app.ContextImpl.openFileInput(ContextImpl.java:780)
	at android.content.ContextWrapper.openFileInput(ContextWrapper.java:179)
	at mqq.app.MobileQQ.loadProperites(MobileQQ.java:232)
	at mqq.app.MobileQQ.doInit(MobileQQ.java:158)
	at mqq.app.MobileQQ.waitAppRuntime(MobileQQ.java:815)
	at com.tencent.mobileqq.pluginsdk.ipc.PluginRemoteService$Sub2.onCreate(PluginRemoteService.java:60)
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:2644)
	at android.app.ActivityThread.access$1700(ActivityThread.java:138)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1524)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:156)
	at android.app.ActivityThread.main(ActivityThread.java:5111)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at android.os.Process$1.run(Process.java:418)
Caused by: libcore.io.ErrnoException: open failed: ENOENT (No such file or directory)
	at libcore.io.Posix.open(Native Method)
	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:110)
	at libcore.io.IoBridge.open(IoBridge.java:393)
	... 16 more
[87,3061053504:01:22:52.911652] Native Client module will be loaded at base address 0x000000005c080000
E/libcommon:       nacl_list_mappings failed with errno:38

**Comment by ssfdust** [comment]
the same problem here, the reason might be that the apk file was not installed successfully.I use es file manager to find there aren't any folders related to mobileqq under the /data/data directory.
I have an idea, but I can't manage it for none root privilege.It's that copying /data/data/com.tencent.mobileqq/ from your andriod phone to the ARChon filesystem.
Maybe hacking filesystem.js helps.
ssfdust

**Comment by sevk** [comment]
can't reappear . so close .
