### ISSUE TITLE
Chromeos-apk doesn't work yet. Could you help me? I've tried to run an apk by chrome apk but it doesn't work.

### ISSUE THREAD

**Issue by IvanCastaneda** [vladikoff/chromeos-apk#289]
/usr/local/lib/node_modules/chromeos-apk/node_modules/adm-zip/zipFile.js:31
		let index = mainHeader.offset; // offset of first CEN header
		^^^
SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/chromeos-apk/node_modules/adm-zip/adm-zip.js:8:12)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)

**Comment by jpearce11** [comment]
I'm having the same issue `chromeos-apk  com.epicgames.fortnite.apk`

The term 'chromeos-apk' is not recognized as the name of a cmdlet, function, script file, or operable program.

**Comment by wallenwarren** [comment]
PS C:\WINDOWS\system32> get-executionpolicy
if "Restricted" chromepos-apk can't work.
Run Windows Powershell with admin

PS C:\WINDOWS\system32> set-executionpolicy remotesigned

Then "Y"

Chromepos-apk work

**Comment by netdev01** [comment]
> PS C:\WINDOWS\system32> set-executionpolicy remotesigned

Mine is already RemoteSigned.  But I am still getting the same error.
